apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: aerocart
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgrespassword
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-order-shard0
  namespace: aerocart
spec:
  serviceName: postgres-order-shard0
  replicas: 1
  selector:
    matchLabels:
      app: postgres-order-shard0
  template:
    metadata:
      labels:
        app: postgres-order-shard0
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: order_db_shard0
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-order-shard0
  namespace: aerocart
spec:
  ports:
    - port: 5432
  selector:
    app: postgres-order-shard0
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-order-shard1
  namespace: aerocart
spec:
  serviceName: postgres-order-shard1
  replicas: 1
  selector:
    matchLabels:
      app: postgres-order-shard1
  template:
    metadata:
      labels:
        app: postgres-order-shard1
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: order_db_shard1
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-order-shard1
  namespace: aerocart
spec:
  ports:
    - port: 5432
  selector:
    app: postgres-order-shard1
