apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: aerocart
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: aerocart/inventory-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-inventory:5432/inventory_db"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: aerocart
spec:
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: inventory-service
